### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by georgefst** [sw3dish/haskify#5]
Given the lack of activity, I'm assuming you have no intention of developing this project further.

I was looking for something like this, and it seems to work with latest GHC and libraries.

So just a heads up that I'm intending to fork this, add most of the remaining endpoints, and put it on Hackage.

Obviously I'll give you credit for doing most of the work.

**Comment by sw3dish** [comment]
@georgefst Go right ahead! I haven't looked at this since we originally hacked it together, but it's neat that there's some interest in it. Looking forward to seeing what you do with it!

**Comment by georgefst** [comment]
In case anyone stumbles across this, I started an almost complete rewrite: https://github.com/georgefst/spotify.

That should become usable in the next few weeks/months once I clean up, document, and add the remaining endpoints.

I copied the main record type definitions from here, so I'll credit you guys anyway.
